### ISSUE TITLE
Certain channel and label combinations can result in duplicate MD5 hashes.

### ISSUE THREAD

**Issue by ryanpoulos** [NIVeriStandAdd-Ons/Ballard-Arinc-429-Custom-Device#1]
In the following VI:

Ballard-Arinc-429-Custom-Device\Source\System Explorer\SubVIs\Parse Parameters File\Read XML_Extra Checks_Check Label Uniqueness For Each hardWareChannel.vi

The hardware channel and label decimal are combined using a Format Into String with the format of "%d%d". However, this can result in duplicate strings, even if the configuration is correct.

For example:
Channel 1 Label 60 results in string "160"
Channel 16 Label 0 results in string "160" also

An easy fix would be to change the format string to be "%02d%03d" (the label needs 3 to prevent issues with values greater than 100).

**Comment by VincentRuault** [comment]
This has been solved in version 1.3.6.
