### ISSUE TITLE
Custom Device incompatible with OmniBus II cards when purchased from Astronics Ballard directly

### ISSUE THREAD

**Issue by Schlammkuh** [NIVeriStandAdd-Ons/Ballard-Arinc-429-Custom-Device#14]
It turns out that OmniBus II cards purchased from Astronics Ballard directly use a different firmware than those purchased from National Instruments (according to Astronics Ballard support). The drivers also differ.
This Custom Device relies on the drivers supplied by National Instruments, which in turn are incompatible with our cards' firmware (card obtained from Astronics Ballard directly). Error code we see is:

BTICardLV.lvlib:Error Converter (ErrCode or Status).vi<ERR>
Encountered library error 403004=ERRTYPE_NOKEY The hardware has not been keyed for use with LabVIEW (LabVIEW Library)
Debug Info: BTICardLV_Initialize did not find a LabVIEW feature key.

<b>Complete call chain:</b>
     BTICardLV.lvlib:Error Converter (ErrCode or Status).vi
     BTICardLV.lvlib:Initialize By Card Number and Core Number.vi
     Card Test.vi

Can you provide a version of the Custom Device that relies on the drivers supplied by Astronics Ballard?

**Comment by VincentRuault** [comment]
Hi,

Is-it going to run on LabVIEW Windows or RT?
For the moment, the Ballard Arinc-429 Custom Device runs only on PharLap RT targets.
You will have to substitute calls to the Ballard driver (NI certified) by calls from the non NI certified driver. It's not something which currently exists and not in our plans. As you said, the HW has some key in the board firmware that makes it specific to one or the other driver.

You can contact me on my NI email address if you have more questions/comments: vincent.ruault@ni.com.

Regards

Vincent

**Comment by Schlammkuh** [comment]
Hi Vincent,
I'm sending you a message from my business email account to continue the discussion.
Thanks for your time.

Sincerely,

Sebastian

**Comment by VincentRuault** [comment]
Hi Sebastian,
I'm closing that Issue.

Regards.
