### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by vinodhini-J** [NIVeriStandAdd-Ons/Ballard-Arinc-429-Custom-Device#21]
Hi,

i have added below the hardware and software details.
When we try to deploy the custom device in veristand, we are getting the below error:

**_ERROR:_**
Deployment Error
Project Window.lvlib:Project Window.vi >> Project Window.lvlib:Command Loop.vi >> Project Window.lvlib:Connect to System.vi
<append>=========================
NI VeriStand:  Open VI Reference in Custom Devices Storage.lvlib:Open Device Reference (HW Interface).vi->Custom Devices Storage.lvlib:Initialize Device (HW Interface).vi->NI VeriStand Engine.lvlib:Initialize Inline Custom Devices.vi->NI VeriStand Engine.lvlib:VeriStand Engine State Machine.vi->NI VeriStand Engine.lvlib:VeriStand Engine.vi->NI VeriStand Engine.lvlib:VeriStand Engine Wrapper (RT).vi<APPEND>
<b>c:\ni-rt\VeriStand\Custom Devices\Ballard - Arinc-429\Ballard - Arinc-429 Engine.llb\Ballard - Arinc-429 RT Driver VI.vi</b>
Error 1003 occurred at Project Window.lvlib:Project Window.vi >> Project Window.lvlib:Command Loop.vi >> Project Window.lvlib:Connect to System.vi

**Possible reason(s):
LabVIEW: (Hex 0x3EB) The VI is not executable.  This error may occur because the VI is either broken or contains a subVI that LabVIEW cannot locate. Select File>>Open to open the VI and verify that you can run it.
=========================**
NI VeriStand:  Open VI Reference in Custom Devices Storage.lvlib:Open Device Reference (HW Interface).vi->Custom Devices Storage.lvlib:Initialize Device (HW Interface).vi->NI VeriStand Engine.lvlib:Initialize Inline Custom Devices.vi->NI VeriStand Engine.lvlib:VeriStand Engine State Machine.vi->NI VeriStand Engine.lvlib:VeriStand Engine.vi->NI VeriStand Engine.lvlib:VeriStand Engine Wrapper (RT).vi<APPEND>
c:\ni-rt\VeriStand\Custom Devices\Ballard - Arinc-429\Ballard - Arinc-429 Engine.llb\Ballard - Arinc-429 RT Driver VI.vi

**_HARDWARE DETAILS:_**
 PXIE-1084 chasis
NI PXIE- 8880 controller
OS in PXI - pharlap
Ballard card - LV-222-442-442

**_SOFTWARE DETAILS:_**
LabVIEW 2019 SP1
Veristand 2019 R3
ARINC ballard driver - 1.3.0.4

Also we tried to monitor the error in console and we got the below error:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/66773333/84469299-5c34dd00-ac9e-11ea-90aa-319276923416.png)

Even when we build a simple Inline-Async custom device (built specifically for RT), its not deploying in veristand with Pharlap OS but the same custom device (built specifically for windows target) is successfully deploying in veristand with windows OS.

It would be grateful if we get a support earlier.

Thanks,
Vino

**Comment by VincentRuault** [comment]
That request was solved outside from the forum.
As a general recommendation, user should use the available releases and not recompile the CD or for good reasons like a feature not available.
