### ISSUE TITLE
Configuration Main VI for LinuxRT version in dev2020 branch search for a VI in PharLap folder

### ISSUE THREAD

**Issue by CyGaNeo** [NIVeriStandAdd-Ons/Ballard-Arinc-429-Custom-Device#28]
Hi,

After applying the steps documented in issue #24 and build configuration and engine LLBs (Linux only for this one) from the project, loading the CD in VS displays a broken page.

Broken page :
Ballard - Arinc-429 Configuration.llb\Ballard - Arinc-429 - Main Page.vi

VeriStand Reported error : 
Error -307832
![image](https://user-images.githubusercontent.com/86322638/122986506-89b26d00-d36d-11eb-9c2a-9c5d18ea0ea0.png)

**Comment by CyGaNeo** [comment]
After building the engine for PharLap (even if I won't use it...), the configuration Main Page is still broken.
But this time no VS error anymore.
![image](https://user-images.githubusercontent.com/86322638/122988215-7bfde700-d36f-11eb-984a-56e13638e926.png)

**Comment by CyGaNeo** [comment]
After opening the Main Page from the built llb, LV asked for the path of SerDes.dll.
Pointing LV to choose the file version 1.2, LV reports a root error being a missing dependency :
![image](https://user-images.githubusercontent.com/86322638/122989069-66d58800-d370-11eb-841e-18967cfc2011.png)

**Comment by CyGaNeo** [comment]
Editing the VI shown in my previous post from the Linux related project shows that the BTI_SerDes.dll cannot be loaded using LabVIEW : 
![image](https://user-images.githubusercontent.com/86322638/122989748-2cb8b600-d371-11eb-9021-9cad07988823.png)

A specific .NET RTE version is needed to load this assembly ?

**Comment by CyGaNeo** [comment]
Windows was blocking the DLL.
Right clicking the dll, the checkbox 'unblock' needs to be checked and modification applied.
LabVIEW needs to be restarted for the modification to be taken into account.

The dependency to PharLap folder is still there however.

**Comment by fmussi** [comment]
@CyGaNeo , thanks for digging into the error with the DLL. Can you work in system Explorer without problems now? 

About the depencency, do you mean the error from VS? This is happening if you don't build the engine build specification for the pharlap target. However, you should be able to deploy the custom device for linux rt. Can you confirm it?

**Comment by CyGaNeo** [comment]
Actually I fixed the DLL issue and built the PharLap engine in a row. So I don't know if the error was preventing me to deploy.
Doing these 2 actions allowed the main page to load.

Other problems appeared after, but I'll open new issues.
I guess you can close this issue when the DLL unblocking will be documented.
