### ISSUE TITLE
Compile Failure

### ISSUE THREAD

**Issue by MatthieuCERTIA** [NIVeriStandAdd-Ons/Ballard-Arinc-429-Custom-Device#4]
Hello,
I try to compile the custom device in 2017-1.3.7-009 version, but don't success.
It seems there is a problem with 2 dll :
- Ballard_BTI_XML_Deserializer.dll
- Parameters_Arinc429_XML_Tools.dll
which are not at the good place or ?
Isn't it possible to get directly a compile version ?
Thank you
Matthieu

**Comment by VincentRuault** [comment]
Hi Matthieu,

Sorry for delayed answer. What error did you get during the compilation? These 2 DLLs are with the source, no? Please contact me on my email address: vincent.ruault@ni.com.

Regards

Vincent

**Comment by VincentRuault** [comment]
Hi @MatthieuCERTIA ,

Do you still have this issue?

Regards

Vincent

**Comment by MatthieuCERTIA** [comment]
Hi Vincent,
It was for a test before buying the device.
Finally we decided to buy another reference of device, so it's not a problem anymore.
Thanks for your answer.
Matthieu
