### ISSUE TITLE
Deployment problems

### ISSUE THREAD

**Issue by slaine13** [NIVeriStandAdd-Ons/Ballard-Arinc-429-Custom-Device#5]
Hi, 
I've been trying to get this working without much success... System is an NI real time chassis, running RT 2016 and VeriStand 2016. The host is running windows 7 64 bit.
I can build the configuration and engine llb's ok, but when I try and deploy to the realtime box, I get a 1003 error saying that the RT driver vi is 'either broken or contains a subVI that LabVIEW cannot locate'
I was looking at the NI AIT version, and noticed that the real time drivers require that the 32 bit version is installed on the host, to allow the RT drivers to be installed. Is there maybe some similar issue with the Ballard card? (*the Ballard RT files are successfully installed on the RT target, but just wondering about a mismatch if the llb's are using the 64 bit version...)

Unfortunately the Astronics/Ballard driver only allows the 64 bit version to be installed on a 64 bit machine, so I can't easily try the alternative, unless I find an alternative host machine...
Any other suggestions would be gratefully received

**Comment by VincentRuault** [comment]
Hi,
I'm sorry to read you are having troubles with the custom device (CD).

On a side note, you don't need to build the CD yourself, under "Releases", you can find packages, one being for 2016.

I confirm that it's the 64-Bits version of the driver to be installed on host and it's what I have on my Virtual Machine, too.
Few questions:
- Can you use the version coming via a package and confirm whether it works or not? 
- What  is the model of your Arinc-429 board?
- Can you see the board core in MAX?
- What is the HW configuration file you are deploying? Can you share it with me?

Regards

Vincent

**Comment by slaine13** [comment]
Hi Vincent,
 Many thanks for your quick reply.
Things have moved on a bit... I found that my problem seems to be from messing with the drivers installed initially, and then messing with the engine side exclusions... seems I had tried to move the RT bits into Labview proper, and hit some depreciated vi's... 
I tried a fresh version today, and got a 'nicer' error message which enabled me to use some debug messages written to the console that pinned it down to the channels I had inherited from elsewhere, and the seemingly fixed 32 channels that are looked at for channel handles. I shrunk that down to the 8 channels that are in the XML and now I can get it to run...
Ideally I'd read how many channels are defined, and scale the for loop on getting the channel handles to that number.. Any clues on that?
The card is still in a chassis away from the real unit, but no longer errors...
The next stage will be to put the ARINC card back into the proper chassis, and see if I get any messages that make sence.
I had contacted Ballard support, and they were less than helpful... just said which driver they'd recommend, and that to look at the NI examples... this github example wasn't official :(

My next task is to how to put the device I'm trying to talk to in the correct xml format... I guess you can tell I'm fairly new to this ;) I've worked on this device for quite a while, but previously, we were using custom hardware via a usb interface...

If you can shed any light on structuring the xml files, I'd be in your debt... 
I guess the acid test is whether it seems ok in the ballard xml editor? 

The hardware is a astronics/ballard card sourced from NI... the LV-222-441-000 card.
Yes, I can see it in MAX, although the PXI slot info doesn't make sense... PXI9 in a 4 slot chassis? I'm guessing the Ballard configuration sw can change that, but using card 0, core 0 seems to bear more fruit...
I'll have to check if I can share the HW config file with you... Aerospace, even with civil aircraft, are quite careful... lots of international constraints, which really don't help in collaboration on technical issues...

Once again, although I've seemed to get past my original problems, I really appreciate your help, and hope I can contact you again if/when I have further problems...

John

**Comment by slaine13** [comment]
To complicate things further, I've just had a laptop upgrade  :| 
So tomorrow my main task will be to try and get to the same point I am now... It's a mega machine, so I'm thinking I'll just see problems quicker <ha ha> :)

**Comment by VincentRuault** [comment]
Hi John,
- If you use a recent version of the custom device, you can specify the card you want to play using PXI Slot number and not the Ballard card number which is something you cannot really determine how it's assigned. 
- For the Hardware XML, you can use the BTIXMLEditor which gives you really basic features. But it's not really reliable and will often crash. Moreover, there are some checking not performed. It's limited to the validation against XML Schema (and it's also what we do in the custom device (in System Explorer) when load the HW configuration file. We also perform other extra checking.

I don't need your HW file and I know it's often something customers can't share.
Keep me updated. You can contact me on my NI address (vincent.ruault@ni.com) if you cannot get help.

Regards

Vincent

**Comment by vinodhini-J** [comment]
Hi John,

Is that issue resolved for you? 

Vino

**Comment by VincentRuault** [comment]
Hi, 

This issue is closed. You should open a new one if you have a question.

Regards

Vincent
